# Modify for your needs, should be a array of objects with a friendly label of whats notified and the URL to scrape
sites:
   - label: Einburgerung pankow
    url: https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=327427&anliegen[]=318998&herkunft=1

# Set true to allow multiple notifications for the same appointment instead of just the first
allow_multiple_notifications: false

# Configure for pushbullet support
pushbullet:
  api_token: o.eaDNHpk1wVKWSYfDas2D74OIKDmuZbl0

# Configure for telegram support
